site_name: My package
theme:
  name: readthedocs
  highlightjs: true
repo_url: https://github.com/dsapalidis/mypackage/tree/main
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx
markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition