<<<<<<< HEAD
[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "mypackage"
version = "0.2.0"
license = {file = "LICENSE.txt"}

description = "My first package"
authors = [{name = "Sapalidis et al."}]
maintainers = [
    {name = "NumPy Developers", email="dsapalidis@gmail.com"},
]
requires-python = ">=3.9"

dependencies = [
    "httpx",
    "gidgethub>4.0.0",
]

[project.optional-dependencies]
dev = [
    "bumpver==2023.1129",
    "pre-commit==3.5.0",
    "pytest==7.4.3",
    "pytest-cov==2.6.1",
]
docs = [
    "sphinx==4.2.0",
    "sphinx-rtd-theme==1.0.0",
]
=======
[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "mypackage"
version = "0.1.0"
license = {file = "LICENSE.txt"}

description = "My first package"
authors = [{name = "Sapalidis et al."}]
maintainers = [
    {name = "NumPy Developers", email="dsapalidis@gmail.com"},
]
requires-python = ">=3.9"

dependencies = [
    "httpx",
    "gidgethub>4.0.0",
]

[project.optional-dependencies]
dev = [
    "bumpver==2023.1129",
    "pre-commit==3.5.0",
    "pytest==7.4.3",
    "pytest-cov==2.6.1",
]
docs = [
    "sphinx==4.2.0",
    "sphinx-rtd-theme==1.0.0",
]
>>>>>>> 022a6571e5bf9ce34b3190140acb06061541d3fb
